"""procurement: tender_items, requirements (fase 6)

Revision ID: 4f7180d7c953
Revises: 751d998f6213
Create Date: 2026-09-17 14:26:14.130415

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f7180d7c953"
down_revision: str | None = "751d998f6213"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender_items",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("item_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("material_or_service", sa.String(length=30), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_of_measure", sa.String(length=60), nullable=True),
        sa.Column("unit_estimated_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("total_estimated_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tender_id", "item_number", name="uq_tender_items_item_number"),
    )
    op.create_index(op.f("ix_tender_items_tender_id"), "tender_items", ["tender_id"], unique=False)
    op.create_table(
        "requirements",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=200), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id", "chunk_index", name="uq_requirements_document_chunk"
        ),
    )
    op.create_index(op.f("ix_requirements_category"), "requirements", ["category"], unique=False)
    op.create_index(
        op.f("ix_requirements_document_version_id"),
        "requirements",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_requirements_tender_id"), "requirements", ["tender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requirements_tender_id"), table_name="requirements")
    op.drop_index(op.f("ix_requirements_document_version_id"), table_name="requirements")
    op.drop_index(op.f("ix_requirements_category"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_tender_items_tender_id"), table_name="tender_items")
    op.drop_table("tender_items")
    # ### end Alembic commands ###
