"""document_versions: add page_texts (Fase 5 chunking precisa de limites de pagina)

Revision ID: 751d998f6213
Revises: 9ee12055f5e2
Create Date: 2026-09-17 12:52:39.043988

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "751d998f6213"
down_revision: str | None = "9ee12055f5e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default so para as linhas existentes (Fase 4 ja tem DocumentVersion em producao/dev)
    # — removido em seguida porque o modelo usa default Python (list), nao server_default.
    op.add_column(
        "document_versions",
        sa.Column(
            "page_texts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.alter_column("document_versions", "page_texts", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_versions", "page_texts")
    # ### end Alembic commands ###
