"""document intelligence: documents, document_versions, tender_documents.document_id

Revision ID: 9ee12055f5e2
Revises: bd8fbab1d81d
Create Date: 2026-09-16 22:30:48.020109

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ee12055f5e2"
down_revision: str | None = "bd8fbab1d81d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("latest_version_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=True)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("processing_version", sa.String(length=20), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum("NATIVE", "OCR", "VISION", "HYBRID", name="extraction_method"),
            nullable=False,
        ),
        sa.Column(
            "extraction_quality",
            sa.Enum("HIGH", "MEDIUM", "LOW", "UNUSABLE", name="extraction_quality"),
            nullable=False,
        ),
        sa.Column("ocr_required", sa.Boolean(), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column(
            "layout_quality",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="layout_quality"),
            nullable=False,
        ),
        sa.Column(
            "table_quality",
            sa.Enum("HIGH", "MEDIUM", "LOW", "NOT_APPLICABLE", name="table_quality"),
            nullable=False,
        ),
        sa.Column("low_extraction_confidence", sa.Boolean(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_number", name="uq_document_versions_number"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.add_column("tender_documents", sa.Column("document_id", sa.UUID(), nullable=True))
    op.add_column("tender_documents", sa.Column("processing_error", sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_tender_documents_document_id", "tender_documents", "documents", ["document_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tender_documents_document_id", "tender_documents", type_="foreignkey")
    op.drop_column("tender_documents", "processing_error")
    op.drop_column("tender_documents", "document_id")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###

    # op.drop_table nao remove o tipo ENUM associado (ver migrations anteriores).
    op.execute("DROP TYPE IF EXISTS extraction_method")
    op.execute("DROP TYPE IF EXISTS extraction_quality")
    op.execute("DROP TYPE IF EXISTS layout_quality")
    op.execute("DROP TYPE IF EXISTS table_quality")
