"""procurement: tenders, tender_versions, tender_documents

Revision ID: bd8fbab1d81d
Revises: 1fa047318986
Create Date: 2026-09-16 22:02:07.554388

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd8fbab1d81d"
down_revision: str | None = "1fa047318986"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenders",
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("orgao_cnpj", sa.String(length=14), nullable=False),
        sa.Column("orgao_nome", sa.String(length=255), nullable=False),
        sa.Column("unidade_nome", sa.String(length=255), nullable=True),
        sa.Column("modalidade", sa.String(length=60), nullable=False),
        sa.Column("objeto", sa.Text(), nullable=False),
        sa.Column("valor_estimado", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("data_publicacao", sa.Date(), nullable=True),
        sa.Column("data_abertura_proposta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_encerramento_proposta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("situacao", sa.String(length=60), nullable=True),
        sa.Column("latest_version_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_tenders_source_external_id"),
    )
    op.create_index(op.f("ix_tenders_external_id"), "tenders", ["external_id"], unique=False)
    op.create_index(op.f("ix_tenders_orgao_cnpj"), "tenders", ["orgao_cnpj"], unique=False)
    op.create_table(
        "tender_documents",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("external_document_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("download_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tender_id", "external_document_id", name="uq_tender_documents_external_id"
        ),
    )
    op.create_index(
        op.f("ix_tender_documents_tender_id"), "tender_documents", ["tender_id"], unique=False
    )
    op.create_table(
        "tender_versions",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tender_id", "content_hash", name="uq_tender_versions_hash"),
        sa.UniqueConstraint("tender_id", "version_number", name="uq_tender_versions_number"),
    )
    op.create_index(
        op.f("ix_tender_versions_tender_id"), "tender_versions", ["tender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tender_versions_tender_id"), table_name="tender_versions")
    op.drop_table("tender_versions")
    op.drop_index(op.f("ix_tender_documents_tender_id"), table_name="tender_documents")
    op.drop_table("tender_documents")
    op.drop_index(op.f("ix_tenders_orgao_cnpj"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_external_id"), table_name="tenders")
    op.drop_table("tenders")
    # ### end Alembic commands ###
