"""core: tenants, domain_events, job_runs

Revision ID: be4092dc1bdd
Revises: 
Create Date: 2026-09-16 20:59:47.693630

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be4092dc1bdd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_tenant_id'), 'domain_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_domain_events_topic'), 'domain_events', ['topic'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenant_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('job_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_tenant_id'), 'job_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Isolamento multi-tenant via Row-Level Security (ver ADR-0002, SECURITY_MODEL.md) ---
    # FORCE (nao so ENABLE) e necessario porque a conexao da aplicacao e dona da tabela, e o
    # Postgres isenta o dono da tabela das politicas de RLS por padrao a menos que FORCE seja
    # aplicado. Sem isso, RLS existiria "no papel" mas nao seria de fato aplicado.
    op.execute("ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_runs FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation_job_runs ON job_runs
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation_job_runs ON job_runs")
    op.execute("ALTER TABLE job_runs NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_runs DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_runs_tenant_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_domain_events_topic'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_tenant_id'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###

    # op.drop_table nao remove o tipo ENUM associado no Postgres — sem isso, um upgrade
    # subsequente falha com "type already exists".
    op.execute("DROP TYPE IF EXISTS job_status")
    op.execute("DROP TYPE IF EXISTS tenant_status")
